---
title: "Lean_data_exploration_2/15"
output: 
  html_document: 
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(RColorBrewer)
library(paletteer)
library(janitor)
library(here)
library(skimr)
library(ggthemes)
library(naniar)
library(readr)
library(shiny)
library(shinydashboard)
options(scipen=999)
if (!require("tidyverse")) install.packages('tidyverse')
```

This is a preloading of the data. The original publication can be found [here](https://doi.org/10.1038/nature16532) and it was also mentioned in [this paper.](https://doi.org/10.1111/2041-210X.12779).
```{r}
nectar_perflower <- read_csv(here("potential_datasets", "AgriLand_Nectar_perflower.csv"))
```

```{r}
nectar_perflower
```

```{r}
nectar_perflower_clean <- nectar_perflower %>% 
  clean_names() %>% 
  mutate_all(tolower) %>% 
  separate(species,
           into = c("genus", "epithet")) %>% 
  separate(bagging_date,
           into = c("bagging_day", "bagging_month", "bagging_year"),
           sep = "/") %>% 
  separate(collection_date,
           into = c("collection_day", "collection_month", "collection_year"),
           sep = "/") %>% 
  separate(habitat,
           into = c("habitat_class", "habitat_specific"),
                    sep = "-",
                    extra = "merge") %>% 
  separate(collection_hour,
           into = c("collection_hour", "collection_minute", "collection_second"),
           sep = ":") %>% 
  separate(bagging_hour,
           into = c("bagging_hour", "bagging_minute", "bagging_second"),
           sep = ":")
```



```{r}
nectar_perflower_clean$sugar_in_micrograms_flower_24h <- as.numeric(nectar_perflower_clean$sugar_in_micrograms_flower_24h)
nectar_perflower_clean$sugarmax_in_micrograms_flower_24h <- as.numeric(nectar_perflower_clean$sugarmax_in_micrograms_flower_24h)
nectar_perflower_clean$hum <- as.numeric(nectar_perflower_clean$hum)
nectar_perflower_clean$temp <- as.numeric(nectar_perflower_clean$temp)
nectar_perflower_clean$year <- as.numeric(nectar_perflower_clean$year)
```


```{r}
nectar_perflower_clean
```

#### Note: NA's are removed

#### Biological Analyses
######How do time of day, flower age, and flower sex affect the amount of nectar per flower?


```{r}
nectar_perflower_clean %>% 
  filter(sugar_in_micrograms_flower_24h!="NA", flower_sex!="NA") %>% 
  select(flower_sex, sugar_in_micrograms_flower_24h) %>% 
  group_by(flower_sex) %>% 
  summarise(total_nectar = sum(sugar_in_micrograms_flower_24h)) %>% 
  arrange(desc(total_nectar))
```



```{r}
nectar_perflower_clean %>% 
  filter(sugar_in_micrograms_flower_24h!="NA", flower_age!="NA") %>% 
  select(flower_age, sugar_in_micrograms_flower_24h) %>% 
  group_by(flower_age) %>% 
  summarise(total_nectar = sum(sugar_in_micrograms_flower_24h)) %>% 
  arrange(desc(total_nectar))
```



```{r}
nectar_perflower_clean %>% 
  filter(sugar_in_micrograms_flower_24h!="NA", collection_hour!="NA") %>% 
  select(collection_hour, sugar_in_micrograms_flower_24h) %>% 
  group_by(collection_hour) %>% 
  summarise(total_nectar = sum(sugar_in_micrograms_flower_24h)) %>% 
  arrange(desc(total_nectar))
```
 


## Shiny App Showing Different Factors that Affect Nectar Production
```{r}
ui <- dashboardPage(skin="black",
  dashboardHeader(title = "Why are Insect Pollinator Communities Declining?",
                  titleWidth = 550),
  dashboardSidebar(disable = T),
  dashboardBody(
  fluidRow(
  box(title = "Variables Affecting Nectar Production", width = 3,
  selectInput("x", "Select Variable:", choices = c("year", "temp", "hum", "collection_hour", "flower_sex", "flower_age"),
              selected = "year"),
  hr(),
      helpText("Reference: Baude M, Kunin W, Boatman N, Davies N, Gillespie M, Morton D, Smart S, Memmott J. Historical nectar assessment reveals the fall and rise of floral resources in Britain. 2016.")
  ), 
  box(title = "Amount of Nectar Produced", width = 6,
  plotOutput("plot", width = "600px", height = "500px")
  ) 
  ) 
  ) 
)

server <- function(input, output, session) { 
  
  output$plot <- renderPlot({
  nectar_perflower_clean %>%
    filter(flower_sex!="NA", flower_age!="NA", sugar_in_micrograms_flower_24h!="NA", sugar_in_micrograms_flower_24h!="0.0000000",  year!="NA", temp!="NA", hum!="NA", collection_hour!="NA") %>%
    ggplot(aes_string(x=input$x)) + 
    geom_bar(position="dodge", color="black", fill="chartreuse4", alpha=0.7) +
    ggthemes::theme_pander(base_size = 13) +
    labs(y = "Nectar Produced (mg)")
  })
  
  session$onSessionEnded(stopApp)
  }

shinyApp(ui, server)
```




